import { QRStyle } from '@/lib/types';

export interface QRTemplate {
  id: string;
  name: string;
  description: string;
  style: QRStyle;
}

export const QR_TEMPLATES: QRTemplate[] = [
  {
    id: 'classic-black',
    name: 'Classic Black',
    description: 'Timeless and crisp — works everywhere',
    style: {
      fgColor: '#000000',
      bgColor: '#ffffff',
      gradientType: 'solid',
      dotsType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      errorCorrection: 'M',
      frame: 'none',
    },
  },
  {
    id: 'midnight-ocean',
    name: 'Midnight Ocean',
    description: 'Deep blue gradient with rounded dots',
    style: {
      gradientType: 'diagonal',
      gradientColor1: '#0ea5e9',
      gradientColor2: '#1e3a8a',
      bgColor: '#ffffff',
      dotsType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'emerald-mist',
    name: 'Emerald Mist',
    description: 'Fresh green gradient, soft rounded shape',
    style: {
      gradientType: 'vertical',
      gradientColor1: '#10b981',
      gradientColor2: '#065f46',
      bgColor: '#f0fdf4',
      dotsType: 'extra-rounded',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'sunset-blaze',
    name: 'Sunset Blaze',
    description: 'Warm orange-to-red diagonal gradient',
    style: {
      gradientType: 'diagonal',
      gradientColor1: '#f59e0b',
      gradientColor2: '#dc2626',
      bgColor: '#fffbeb',
      dotsType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'royal-plum',
    name: 'Royal Plum',
    description: 'Magenta-to-violet radial burst',
    style: {
      gradientType: 'radial',
      gradientColor1: '#ec4899',
      gradientColor2: '#7c3aed',
      bgColor: '#ffffff',
      dotsType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'mono-dots',
    name: 'Mono Dots',
    description: 'Minimal black dots on white — modern',
    style: {
      fgColor: '#111827',
      bgColor: '#ffffff',
      gradientType: 'solid',
      dotsType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'M',
      frame: 'none',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    description: 'Elegant pink-gold horizontal gradient',
    style: {
      gradientType: 'horizontal',
      gradientColor1: '#fb7185',
      gradientColor2: '#b45309',
      bgColor: '#fff1f2',
      dotsType: 'classy',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'forest-pine',
    name: 'Forest Pine',
    description: 'Calm teal-to-green vertical gradient',
    style: {
      gradientType: 'vertical',
      gradientColor1: '#14b8a6',
      gradientColor2: '#166534',
      bgColor: '#f0fdfa',
      dotsType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'crimson-luxe',
    name: 'Crimson Luxe',
    description: 'Bold red with classy rounded dots',
    style: {
      gradientType: 'solid',
      fgColor: '#b91c1c',
      bgColor: '#fef2f2',
      dotsType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    description: 'Electric cyan-to-violet diagonal',
    style: {
      gradientType: 'diagonal',
      gradientColor1: '#06b6d4',
      gradientColor2: '#6366f1',
      bgColor: '#0f172a',
      dotsType: 'rounded',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'caramel-swirl',
    name: 'Caramel Swirl',
    description: 'Amber-to-brown radial warmth',
    style: {
      gradientType: 'radial',
      gradientColor1: '#fbbf24',
      gradientColor2: '#92400e',
      bgColor: '#fffbeb',
      dotsType: 'extra-rounded',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    description: 'Soft violet horizontal gradient',
    style: {
      gradientType: 'horizontal',
      gradientColor1: '#a78bfa',
      gradientColor2: '#6d28d9',
      bgColor: '#faf5ff',
      dotsType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    description: 'Pink-to-orange diagonal pop',
    style: {
      gradientType: 'diagonal',
      gradientColor1: '#fb7185',
      gradientColor2: '#f97316',
      bgColor: '#ffffff',
      dotsType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    description: 'Icy blue vertical gradient',
    style: {
      gradientType: 'vertical',
      gradientColor1: '#60a5fa',
      gradientColor2: '#0c4a6e',
      bgColor: '#f0f9ff',
      dotsType: 'classy',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'obsidian-frame',
    name: 'Obsidian Frame',
    description: 'Black classy dots with caption frame',
    style: {
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      gradientType: 'solid',
      dotsType: 'classy',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'caption',
      frameColor: '#0f172a',
      caption: 'Scan Me',
    },
  },
  {
    id: 'spring-bloom',
    name: 'Spring Bloom',
    description: 'Green-to-pink diagonal freshness',
    style: {
      gradientType: 'diagonal',
      gradientColor1: '#84cc16',
      gradientColor2: '#db2777',
      bgColor: '#fefce8',
      dotsType: 'extra-rounded',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
  {
    id: 'graphite-rounded',
    name: 'Graphite Rounded',
    description: 'Slate gray with extra-rounded dots',
    style: {
      gradientType: 'solid',
      fgColor: '#334155',
      bgColor: '#f8fafc',
      dotsType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'M',
      frame: 'rounded',
      frameColor: '#334155',
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Gold radial gradient on cream',
    style: {
      gradientType: 'radial',
      gradientColor1: '#fde68a',
      gradientColor2: '#b45309',
      bgColor: '#fffbeb',
      dotsType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      errorCorrection: 'H',
      frame: 'none',
    },
  },
];

export function getTemplate(id?: string): QRTemplate | undefined {
  if (!id) return undefined;
  return QR_TEMPLATES.find((t) => t.id === id);
}
